runtime: nodejs
env: flex

env_variables:
  DB_USER: root
  DB_PASS: linking7
  DB_NAME: bunkydb
  DB_DIALECT: mysql
  INSTANCE_CONNECTION_NAME: bunkybackend:us-east1:bunkydatabase
  JWT_SECRET: 666hihi666

beta_settings:
  cloud_sql_instances: bunkybackend:us-east1:bunkydatabase
